#include "Analysis/Models/interface/RooDoubleCB.h"
#include "Analysis/Models/interface/RooExpGausExp.h"
#include "Analysis/Models/interface/RooGausExp.h"
#include "Analysis/Models/interface/RooExpBWExp.h"
#include "Analysis/Models/interface/RooPhaseSpace.h"
#include "Analysis/Models/interface/RooPhaseSpacePol4.h"
#include "Analysis/Models/interface/RooRelBreitWigner.h"
#include "Analysis/Models/interface/RooQuadGausExp.h"
#include "Analysis/Models/interface/RooMyNovosibirsk.h"
#include "Analysis/Models/interface/RooExtendNovosibirsk.h"
#include "Analysis/Models/interface/RooDoubleGausExp.h"
#include "Analysis/Models/interface/RooSuperNovosibirsk.h"
#include "Analysis/Models/interface/RooPolyDijet.h"
#include "Analysis/Models/interface/RooSuperDiJet.h"
#include "Analysis/Models/interface/RooGaussianErf.h"


//  for backward compatibility
//  don´t add anything below
//  eventually remove all that
#include "Analysis/Models/interface/2016/RooDoubleCB.h"
#include "Analysis/Models/interface/2016/RooExpGausExp.h"
#include "Analysis/Models/interface/2016/RooGausExp.h"
#include "Analysis/Models/interface/2016/RooExpBWExp.h"
#include "Analysis/Models/interface/2016/RooPhaseSpace.h"
#include "Analysis/Models/interface/2016/RooPhaseSpacePol4.h"
#include "Analysis/Models/interface/2016/RooRelBreitWigner.h"
#include "Analysis/Models/interface/2016/RooQuadGausExp.h"
#include "Analysis/Models/interface/2016/RooMyNovosibirsk.h"
#include "Analysis/Models/interface/2016/RooExtendNovosibirsk.h"
#include "Analysis/Models/interface/2016/RooDoubleGausExp.h"
#include "Analysis/Models/interface/2016/RooSuperNovosibirsk.h"
#include "Analysis/Models/interface/2016/RooPolyDijet.h"
#include "Analysis/Models/interface/2016/RooSuperDiJet.h"
