#include "Analysis/Models/interface/RooDoubleCB.h"
#include "Analysis/Models/interface/RooExpGausExp.h"
#include "Analysis/Models/interface/RooGausExp.h"
#include "Analysis/Models/interface/RooExpBWExp.h"
#include "Analysis/Models/interface/RooPhaseSpace.h"
#include "Analysis/Models/interface/RooPhaseSpacePol4.h"
#include "Analysis/Models/interface/RooRelBreitWigner.h"
#include "Analysis/Models/interface/RooQuadGausExp.h"
#include "Analysis/Models/interface/RooMyNovosibirsk.h"
#include "Analysis/Models/interface/RooExtendNovosibirsk.h"
#include "Analysis/Models/interface/RooDoubleGausExp.h"
#include "Analysis/Models/interface/RooSuperNovosibirsk.h"
#include "Analysis/Models/interface/RooPolyDijet.h"
#include "Analysis/Models/interface/RooSuperDiJet.h"
#include "Analysis/Models/interface/RooBackgroundModel.h"  // for backward compatibility
